_wandb:
    value:
        cli_version: 0.29.0
        e:
            gq8c9og6ye26d96ub4rp9elb7cr5h6w0:
                codePath: 11_vocab8k_next.py
                codePathLocal: 11_vocab8k_next.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "224818880512"
                        used: "51112636416"
                email: lightel@gmail.com
                executable: /home/felix/ai-env/bin/python
                gpu: NVIDIA GeForce RTX 5060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 4608
                      memoryTotal: "17103323136"
                      name: NVIDIA GeForce RTX 5060 Ti
                      uuid: GPU-8a13f23f-4a1a-3040-45a2-60e7398e5168
                host: felix-5060ti
                memory:
                    total: "33452613632"
                os: Linux-7.0.0-30-generic-x86_64-with-glibc2.39
                program: /home/felix/day11/11_vocab8k_next.py
                python: CPython 3.12.3
                root: /home/felix/day11
                startedAt: "2026-09-05T13:06:35.327997Z"
                writerId: gq8c9og6ye26d96ub4rp9elb7cr5h6w0
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.29.0
            "12": 0.29.0
            "13": linux-x86_64
hidden:
    value: 768
seq:
    value: 512
task:
    value: next-token
vocab:
    value: 8000
