FROM nvidia/cuda:12.9.0-devel-ubuntu22.04
RUN apt-get update && apt-get install -y python3 python3-pip python3-dev build-essential
RUN pip install torch --index-url https://download.pytorch.org/whl/cu128
RUN pip install fastapi uvicorn
COPY app_torch_compile.py .
CMD ["python3", "app_torch_compile.py"]
