_wandb:
    value:
        cli_version: 0.29.0
        e:
            20awfgmqv793jrb0rhqizgydqlbakpo4:
                codePath: day09/09_vocab32k_67m.py
                codePathLocal: 09_vocab32k_67m.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "224818880512"
                        used: "50727014400"
                email: lightel@gmail.com
                executable: /home/felix/ai-env/bin/python
                git:
                    commit: 39dd2e2b7d1e002e2c28027c689ed6d33534ee9d
                    remote: git@github.com:Felix-Edgar-Song/ai-1year.git
                gpu: NVIDIA GeForce RTX 5060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 4608
                      memoryTotal: "17103323136"
                      name: NVIDIA GeForce RTX 5060 Ti
                      uuid: GPU-8a13f23f-4a1a-3040-45a2-60e7398e5168
                host: felix-5060ti
                memory:
                    total: "33452613632"
                os: Linux-7.0.0-30-generic-x86_64-with-glibc2.39
                program: /home/felix/ai-1year/day09/09_vocab32k_67m.py
                python: CPython 3.12.3
                root: /home/felix/ai-1year/day09
                startedAt: "2026-09-03T14:09:26.997701Z"
                writerId: 20awfgmqv793jrb0rhqizgydqlbakpo4
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.29.0
            "12": 0.29.0
            "13": linux-x86_64
hidden:
    value: 768
seq:
    value: 512
vocab:
    value: 32000
