FROM nvidia/cuda:12.9.0-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends python3 python3-pip python3-dev build-essential curl git && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --no-cache-dir --upgrade pip
WORKDIR /app
RUN python3 -m pip install --no-cache-dir fastapi uvicorn tiktoken transformers
RUN python3 -m pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cu128
RUN python3 -m pip install --no-cache-dir -U flashinfer-python
RUN python3 -m pip install --no-cache-dir vllm
COPY app_vllm_gpt2.py .
CMD ["python3", "-m", "uvicorn", "app_vllm_gpt2:app", "--host", "0.0.0.0", "--port", "8000"]
